version: '3'
services:
  backend:
    build: ./leatheref-api-server/
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./leatheref-api-server:/app
      - bundle-volume:/usr/local/bundle
    ports:
      - 3000:3000
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: mysql:5.7
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3307:3306
  nginx:
    image: bitnami/nginx:1.10.2-r1
    volumes:
      - ./config/nginx:/bitnami/nginx/conf/vhosts
    depends_on:
      - backend
      - frontend
    environment:
      VIRTUAL_HOST: yourproject.docker
      VIRTUAL_PORT: 8080
    ports:
      - 8080:8080
  frontend:
    build:
      context: ./letheref-front/
      dockerfile: Dockerfile
      # dockerfile: Dockerfile-prod
    depends_on:
      - backend
    command: yarn start
    volumes:
      - ./letheref-front:/frontend-app
      - /frontend-app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - 4000:4000
volumes:
  db-volume:
    driver: local
  bundle-volume:
    driver: local